// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-zNvPaytPP2eSCciC0moJFRGpnIk8e8',
    appId: '1:475518176076:web:8861512ca71717b84d9de9',
    messagingSenderId: '475518176076',
    projectId: 'fir-flutter-codelab-ae44e',
    authDomain: 'fir-flutter-codelab-ae44e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ae44e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWAW_yqvSQXw_Ovzjgprg5ic9I-fGA-1M',
    appId: '1:475518176076:android:5dbb036a89fe48aa4d9de9',
    messagingSenderId: '475518176076',
    projectId: 'fir-flutter-codelab-ae44e',
    storageBucket: 'fir-flutter-codelab-ae44e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXIkeMWYYZBJS8oprBy7wrZ1C_3JJnfo8',
    appId: '1:475518176076:ios:4eeb5d89827dab794d9de9',
    messagingSenderId: '475518176076',
    projectId: 'fir-flutter-codelab-ae44e',
    storageBucket: 'fir-flutter-codelab-ae44e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXIkeMWYYZBJS8oprBy7wrZ1C_3JJnfo8',
    appId: '1:475518176076:ios:4eeb5d89827dab794d9de9',
    messagingSenderId: '475518176076',
    projectId: 'fir-flutter-codelab-ae44e',
    storageBucket: 'fir-flutter-codelab-ae44e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
